#!/usr/bin/env bash

# Message Of The Day
# (MOTD)

version=0.1

# The REAL location of this file.
file_location()
{
    SOURCE="${BASH_SOURCE[0]:-$0}";
    while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname -- "$SOURCE"; )" &> /dev/null && pwd 2> /dev/null; )";
    SOURCE="$( readlink -- "$SOURCE"; )";
    [[ $SOURCE != /* ]] && SOURCE="${DIR}/${SOURCE}"; # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
    done
    SCRIPT_DIR="$( cd -P "$( dirname -- "$SOURCE"; )" &> /dev/null && pwd 2> /dev/null; )";
}
file_location



# Parts of this has been taken from neofetch. https://github.com/dylanaraps/neofetch
# This is a customised motd with less built-in than neofetch
# ┌──────────────────────────────────────┐ 
# │                                      │░
# │            SOURCE CONFIG             │░
# │                                      │░
# └──────────────────────────────────────┘░
#  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
. ${SCRIPT_DIR}/logo.conf

# ┌──────────────────────────────────────┐ 
# │                                      │░
# │           SOURCE COMPONENTS          │░
# │                                      │░
# └──────────────────────────────────────┘░
#  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
. ${SCRIPT_DIR}/components/colours
. ${SCRIPT_DIR}/components/bar
. ${SCRIPT_DIR}/components/row
. ${SCRIPT_DIR}/components/columns
. ${SCRIPT_DIR}/components/title

# ┌──────────────────────────────────────┐ 
# │                                      │░
# │           PLUGINS TO RUN             │░
# │                                      │░
# └──────────────────────────────────────┘░
#  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
plugins()
{

    PLUGINS=(

        # Essentially Ordered Plugins.
        "kernel"        # KERNAL MUST BE FIRST PLUGIN. (OS Relies on it)
        "os"            # OS MUST BE THE SECOND PLUGIN. (Others rely on it)

        # All other Plugins
        "hostname"
        "local_ip"
        "public_ip"
        "uptime"
        "cpu_usage"
        "memory"
        "disk"
        "model"
        "systemctl:mysql"   
        "systemctl:php"   
        "systemctl:apache"   
        "systemctl:ssh"   
        "puppet"
        "logo"
    )


    # ┌──────────────────────────────────────┐ 
    # │        Source & Run Plugins          │
    # └──────────────────────────────────────┘
    for plugin in "${PLUGINS[@]}"; do

        IFS=: read plugin_name plugin_parameter <<< $plugin

        filename="get_${plugin_name}"               # Filename
        . ${SCRIPT_DIR}/plugins/$filename                       # Source File
        $filename $plugin_parameter 2> /dev/null   # Run, hide errors
    done

}
plugins


COLUMN1_WIDTH=41
COLUMN1="${LOGO}"


COLUMN2_WIDTH=50
add_line_to_column2 $HOSTNAME
add_row_to_column2 HOST         $HOSTNAME
add_row_to_column2 OS           $OS
add_row_to_column2 MODEL        $MODEL
add_row_to_column2 LOCAL_IP     $LOCAL_IP
add_row_to_column2 PUBLIC_IP    $PUBLIC_IP

add_line_to_column2 SERVICES
add_row_to_column2 APACHE       $APACHE
add_row_to_column2 PHP          $PHP
add_row_to_column2 MYSQL        $MYSQL
add_row_to_column2 SSH          $SSH

add_line_to_column2 NODE
add_row_to_column2 UPTIME       $CPU_USAGE
add_row_to_column2 MEMORY       $MEMORY
add_row_to_column2 DISK         $DISK

add_line_to_column2 PUPPET
add_row_to_column2 RAN          $PUPPET_LASTRAN
add_row_to_column2 LOCKED       $PUPPET_LOCKED
add_row_to_column2 MESSAGE      $PUPPET_MESSAGE

add_line_to_column2 "HELP COMMANDS"
add_row_to_column2 "help" "List custom scripts."
add_row_to_column2 "cheat" "command cheatsheet."

add_line_to_column2 "◣◥"

columns;